default_platform(:ios)
platform :ios do
  desc "Build iOS without codesign (CI stub)"
  lane :build_nocodesign do
    sh("which flutter >/dev/null || exit 1")
    sh("f=$(git ls-files '**/pubspec.yaml' | head -n1); cd $(dirname $f); flutter pub get")
    sh("f=$(git ls-files '**/pubspec.yaml' | head -n1); cd $(dirname $f); flutter build ios --no-codesign")
  end
end
