name: android-build
on:
  workflow_dispatch:
  pull_request:
    paths: [ "**/*.dart", "**/pubspec.yaml", ".github/workflows/android-build.yml" ]
  push:
    branches: [ "main" ]
    paths: [ "**/*.dart", "**/pubspec.yaml", ".github/workflows/android-build.yml" ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Detect Flutter project
        id: detect
        run: |
          if git ls-files '**/pubspec.yaml' | grep -q .; then
            echo "found=true" >> "$GITHUB_OUTPUT"
          else
            echo "found=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Setup Java 17
        if: steps.detect.outputs.found == 'true'
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Setup Flutter
        if: steps.detect.outputs.found == 'true'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
      - name: Build Android (APK/AAB)
        if: steps.detect.outputs.found == 'true'
        run: tools/bin/android-build.sh
      - name: Upload Android Artifacts
        if: steps.detect.outputs.found == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: android-artifacts
          path: |
            **/build/app/outputs/flutter-apk/app-debug.apk
            **/build/app/outputs/bundle/release/*.aab
            build_reports/BuildReport.json
      - name: No Flutter project found (safe pass)
        if: steps.detect.outputs.found != 'true'
        run: echo "No Flutter project yet – build skipped (passing)."
