name: gates
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "build_reports/**"
      - "tools/policies/**"
jobs:
  opa-apk-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install conftest
        run: |
          curl -L https://github.com/open-policy-agent/conftest/releases/download/v0.52.0/conftest_0.52.0_Linux_x86_64.tar.gz | tar xz
          sudo mv conftest /usr/local/bin/
          conftest --version
      - name: Prepare input
        id: prep
        run: |
          REPORT="build_reports/BuildReport.json"
          if [ ! -f "$REPORT" ]; then
            echo "no_report=true" >> "$GITHUB_OUTPUT"
          else
            echo "no_report=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Run OPA gate (max APK 150MB)
        if: steps.prep.outputs.no_report == 'false'
        env:
          MAX_APK_BYTES: "157286400"
        run: |
          cat > input.json <<JSON
          {
            "max_apk_bytes": ${MAX_APK_BYTES},
            "report": $(cat build_reports/BuildReport.json)
          }
          JSON
          conftest test --input json --policy tools/policies input.json
      - name: No report, gate skipped (pass)
        if: steps.prep.outputs.no_report != 'false'
        run: echo "No BuildReport.json yet; passing."
